# Clause CLI - GoReleaser Configuration
# https://goreleaser.com/customization/

project_name: clause

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...

builds:
  - id: clause
    main: ./cmd/clause
    binary: clause
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/clause-cli/clause/internal/cmd.version={{.Version}}
      - -X github.com/clause-cli/clause/internal/cmd.buildTime={{.Date}}
      - -X github.com/clause-cli/clause/internal/cmd.commit={{.Commit}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: clause-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "$artifact"
    artifacts: checksum

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 20
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 30
    - title: 'Others'
      order: 999

release:
  github:
    owner: clause-cli
    name: clause
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Clause {{ .Tag }} - AI-Native Project Scaffolding

    Framework for Organized, Reproducible, and Guided Engineering
  footer: |
    **Full Changelog**: https://github.com/clause-cli/clause/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Installation

    ```bash
    # macOS/Linux
    curl -fsSL https://get.clause.dev | bash

    # Homebrew
    brew install clause-cli/tap/clause

    # Windows
    winget install Clause.ClauseCLI
    ```

# Homebrew tap
brews:
  - name: clause
    tap:
      owner: clause-cli
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    url_template: "https://github.com/clause-cli/clause/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://clause.dev"
    description: "AI-native project scaffolding CLI tool"
    license: "MIT"
    skip_upload: false
    test: |
      system "#{bin}/clause version"

# Winget manifest
winget:
  - name: clause
    publisher: Clause
    short_description: AI-native project scaffolding CLI tool
    license: MIT
    publisher_url: https://clause.dev
    publisher_support_url: https://github.com/clause-cli/clause/issues
    package_identifier: Clause.ClauseCLI
    url_template: "https://github.com/clause-cli/clause/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: false
    goamd64: v1

# Scoop bucket
scoops:
  - name: clause
    bucket:
      owner: clause-cli
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop manifest update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://clause.dev"
    description: "AI-native project scaffolding CLI tool"
    license: MIT

# AUR package
aurs:
  - name: clause-bin
    homepage: "https://clause.dev"
    description: "AI-native project scaffolding CLI tool"
    maintainers:
      - 'Clause Team <team@clause.dev>'
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/clause-bin.git'
    skip_upload: false
    package: |-
      # bin
      install -Dm755 "./clause" "${pkgdir}/usr/bin/clause"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/clause/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/clause/README.md"

# NPM package wrapper
nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://clause.dev
    description: "AI-native project scaffolding CLI tool"
    maintainer: Clause Team <team@clause.dev>
    license: MIT
    vendor: Clause CLI
    bindir: /usr/bin
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    priority: optional
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
